name = "SphericalHarmonicExpansions"
uuid = "504afa71-bae7-47b4-8ec9-3851161806ac"
authors = ["Marija Boberg, Martin Moeddel, and contributors"]
version = "0.1.4"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MultivariatePolynomials = "102ac46a-7ee4-5c85-9060-abc95bfdeaa3"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StaticPolynomials = "62e018b1-6e46-5407-a5a7-97d4fbcae734"
WignerD = "87c4ff3e-34df-11e9-37a7-516cea4e0402"

[compat]
Combinatorics = "1.0"
HDF5 = "0.16, 0.17"
MultivariatePolynomials = "0.4.7"
Reexport = "1.0"
StaticPolynomials = "1.3"
DynamicPolynomials = "0.4.6"
julia = "1.6"

[extras]
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Rotations"]
